# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - .travis.yml

# Enable minification SASS
sass:
  style: compressed

# Site settings
baseurl: ""
url: "https://labs.cloudbase.it/"
google-tracking-id: ""


lang: "en"
author: "Cloudbase Solutions"
title: "Cloudbase LABS"
description: >
  We are bringing OpenStack to the classroom and as part of our effort
  we will teach, mentor and assist a group of 15 students.
keywords: "windows, linux, python, bash, powershell, openstack, hyper-v"

favicon: "/img/favicon.ico"
logo: "/img/logo.png"

404-img: "/img/labtocat.png"
web-app-mode: True

# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

# Blog
post-preview-words: 96
# Items displayed per page
paginate: 5
# Pagination path
paginate_path: "/blog/page:num/"

# Share options
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname: "cloudbaselabs"

syntax-highlight: True

social:
  - title: "github"
    url: "http://github.com/cloudbase/"

  - title: "facebook"
    url: "https://www.facebook.com/CloudbaseSolutions/"

  - title: "twitter"
    url: "http://twitter.com/cloudbaseit"

  - title: "youtube"
    url: "https://www.youtube.com/channel/UCBgH5RqPL4lgxA8gn3rIAFw/videos"

  - title: "flickr"
    url: "https://www.flickr.com/photos/cloudbaseit"

  - title: "linkedin"
    url: "http://www.linkedin.com/company/cloudbase-solutions"

  - title: "google-plus"
    url: "http://github.com/cloudbase/"

  - title: "rss"
    url: "/feed.xml"

# Settings for deploy rake task
username:        "alexandrucoman"
repo:            "labs.cloudbase.it"
branch:          "master"
relative_source: "../labs.cloudbase.it/"
destination:     "../labs.cloudbase.it-pages/"
production_url:  "https://labs.cloudbase.it/"
source_url:      "https://github.com/alexandrucoman/labs.cloudbase.it"
